import { ref, update, onValue, type Unsubscribe } from 'firebase/database';
import { rtdb } from '@/services/firebase';
import type { Question } from '@/utils/types';

/** Shape of the game state stored in RTDB under rooms/{roomId}/game */
export interface RTDBGameState {
  /** All questions for this session (generated by host, shared with all) */
  questions: Question[];
  /** Index of the current question (host advances this) */
  currentIndex: number;
  /** Per-player progress: playerId -> number of correct answers */
  progress: Record<string, number>;
  /** Game phase: countdown, playing, finished */
  phase: 'countdown' | 'playing' | 'finished';
  /** Timestamp when the current question started (for timer sync) */
  questionStartedAt: number;
}

/** Write the initial game state when host starts the game */
export async function initGameState(
  roomId: string,
  questions: Question[],
  playerIds: string[],
): Promise<void> {
  const progress: Record<string, number> = {};
  for (const id of playerIds) {
    progress[id] = 0;
  }

  const gameState: RTDBGameState = {
    questions,
    currentIndex: 0,
    progress,
    phase: 'countdown',
    questionStartedAt: 0,
  };

  await update(ref(rtdb, `rooms/${roomId}`), { game: gameState });
}

/** Subscribe to game state changes for a room */
export function listenToGameState(
  roomId: string,
  callback: (state: RTDBGameState | null) => void,
): Unsubscribe {
  const gameRef = ref(rtdb, `rooms/${roomId}/game`);
  return onValue(gameRef, (snapshot) => {
    callback(snapshot.exists() ? (snapshot.val() as RTDBGameState) : null);
  });
}

/** Record a correct answer for a player (increment progress) */
export async function recordCorrectAnswer(
  roomId: string,
  playerId: string,
  newCount: number,
): Promise<void> {
  await update(ref(rtdb, `rooms/${roomId}/game/progress`), {
    [playerId]: newCount,
  });
}

/** Host advances to the next question */
export async function advanceQuestion(
  roomId: string,
  nextIndex: number,
): Promise<void> {
  await update(ref(rtdb, `rooms/${roomId}/game`), {
    currentIndex: nextIndex,
    questionStartedAt: Date.now(),
  });
}

/** Set the game phase (countdown -> playing -> finished) */
export async function setGamePhase(
  roomId: string,
  phase: RTDBGameState['phase'],
): Promise<void> {
  await update(ref(rtdb, `rooms/${roomId}/game`), { phase });
}
