export type Difficulty = 'easy' | 'medium' | 'hard';
export type Operation = '+' | '-' | '×' | '÷';
export type Language = 'ro' | 'en';
export type GameType = 'mathRace' | 'shapeMatch' | 'memoryGame';
export type GameMode = 'raceToFinish' | 'timedSprint';
export type ShapeMode = 'image' | 'word';

export interface Player {
  id: string;
  name: string;
  avatar: string;
  score: number;
  isHost: boolean;
  isReady: boolean;
}

export interface Room {
  id: string;
  code: string;
  hostId: string;
  players: Player[];
  status: 'waiting' | 'playing' | 'finished';
  settings: GameSettings;
  createdAt: number;
  /** Classroom session fields (set when room is created via teacher flow) */
  classroomSessionId?: string;
  classroomMode?: ClassroomMode;
  globalTimer?: number;
}

export interface GameSettings {
  gameType: GameType;
  gameMode: GameMode;
  difficulty: Difficulty;
  operations: Operation[];
  rounds: number;
  timePerRound: number;
  shapeMode?: ShapeMode;
}

/** Math question (used by Math Race and Timed Sprint) */
export interface Question {
  id: string;
  a: number;
  b: number;
  operation: Operation;
  correctAnswer: number;
  options: number[];
}

/** Shape question (used by Shape Match) */
export interface ShapeQuestion {
  id: string;
  targetShape: string;
  targetLabel: string;
  options: ShapeOption[];
  correctIndex: number;
}

export interface ShapeOption {
  shape: string;
  color: string;
  label: string;
}

/** Memory card (used by Card Flip Memory game) */
export interface MemoryCard {
  id: string;
  pairId: string;
  emoji: string;
  flipped: boolean;
  matched: boolean;
}

export interface GameSession {
  roomId: string;
  currentRound: number;
  totalRounds: number;
  currentQuestion: Question | null;
  scores: Record<string, number>;
  status: 'countdown' | 'question' | 'result' | 'finished';
  timeRemaining: number;
}

export interface UserPreferences {
  language: Language;
  dyslexicFont: boolean;
  soundEnabled: boolean;
}

/* ------------------------------------------------------------------ */
/*  Teacher / Classroom types (Phase 1c)                              */
/* ------------------------------------------------------------------ */

export type ClassroomMode = 'selfPaced' | 'teacherControlled';

/** A teacher profile stored in Firestore */
export interface TeacherProfile {
  uid: string;
  email: string;
  displayName: string;
  createdAt: number;
}

/** A student code generated by the teacher for persistent identity */
export interface StudentCode {
  code: string;
  label: string;
}

/** A classroom session created by a teacher */
export interface ClassroomSession {
  id: string;
  teacherUid: string;
  title: string;
  settings: GameSettings;
  classroomMode: ClassroomMode;
  /** Global timer in seconds (0 = no limit) */
  globalTimer: number;
  studentCodes: StudentCode[];
  /** RTDB room ID once session is started */
  roomId?: string;
  status: 'draft' | 'active' | 'finished';
  createdAt: number;
}

/** A reusable template saved by a teacher */
export interface SessionTemplate {
  id: string;
  teacherUid: string;
  name: string;
  settings: GameSettings;
  classroomMode: ClassroomMode;
  globalTimer: number;
  /** Custom questions (optional) */
  customQuestions?: CustomQuestion[];
  createdAt: number;
}

/** A custom question created by a teacher */
export interface CustomQuestion {
  id: string;
  text: string;
  options: string[];
  correctIndex: number;
}

/** Per-student result in a classroom session */
export interface StudentSessionResult {
  studentCode: string;
  studentLabel: string;
  score: number;
  totalQuestions: number;
  accuracy: number;
  timeTaken: number;
  answers: StudentAnswer[];
}

export interface StudentAnswer {
  questionIndex: number;
  selectedAnswer: string;
  correct: boolean;
  timeSpent: number;
}
